# Default values for productcatalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


component:
  # Specifies whether a service account should be created
  id: TMFC001
  name: productcatalogmanagement
  functionalBlock: CoreCommerce
  publicationDate: 2023-08-18T00:00:00.000Z
  version: "0.0.1"
  storageClassName: default
security:
  controllerRole: Admin
mongodb:
  port: 27017
  database: tmf
api:
  image: csotiriou/productcatalogapi:0.10
  versionlabel: productcatalogapi-0.10
  otlp:
    console:
      enabled: false
    protobuffCollector:
      enabled: true
      url: http://datadog-agent.default.svc.cluster.local:4318/v1/traces
partyrole:
  image: lesterthomas/partyroleapi:1.0
  versionlabel: partyroleapi-1.0

# Basic nopo11y configurations, requires Nopo11y stack. Ref: https://github.com/znsio/nopo11y
# Additional options are available at https://github.com/znsio/nopo11y/tree/main/charts/nopo11y#configuration
nopo11y:
  enabled: false # Enabling it will give you basic dashboard with golden signals, alerts and SLOs.
  namespace: observability # use the same namespace you used during installation of nopo11y stack
  appLabel: "sample" # Replace it with your app label
  includeReleaseNameInMetricsLabels: true
  deploymentName: "sample" # Replace it with your deployment name