# Default values for productcatalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


component:
  type: productinventory
  name: productinventory
  functionalBlock: CoreCommerce
  publicationDate: 2023-08-18T00:00:00.000Z
  version: "0.0.1"
service:
  type: ClusterIP
  port: 80
security:
  controllerRole: Admin
mongodb:
  port: 27017
  database: tmf
partyrole:
  image: lesterthomas/partyroleapi:1.0
  versionlabel: partyroleapi-1.0

# Basic nopo11y configurations, requires Nopo11y stack. Ref: https://github.com/znsio/nopo11y
# Additional options are available at https://github.com/znsio/nopo11y/tree/main/charts/nopo11y#configuration
nopo11y:
  enabled: false # Enabling it will give you basic dashboard with golden signals, alerts and SLOs.
  namespace: observability # use the same namespace you used during installation of nopo11y stack
  appLabel: "sample" # Replace it with your app label
  includeReleaseNameInMetricsLabels: true
  deploymentName: "sample" # Replace it with your deployment name